version: "3.8"
services:
  servicio-backend:
    container_name: contenedor-jdk11
    image: super-heroe:v2.0
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile            
    ports:
      - 8585:8585
    environment:
      server.port: 8585 
    volumes:
      - ./:/app    
    networks:
       - redprincipal
      
networks:                     
    redprincipal: